begin;

do $$
begin
  if to_regclass('public.table_sessions') is null then
    raise exception 'MODARA-007 requires public.table_sessions';
  end if;

  if to_regclass('public.customer_sessions') is null then
    raise exception 'MODARA-007 requires public.customer_sessions';
  end if;

  if to_regclass('public.orders') is null then
    raise exception 'MODARA-007 requires public.orders';
  end if;
end $$;

lock table public.table_sessions in share row exclusive mode;
lock table public.customer_sessions in share row exclusive mode;
lock table public.orders in share row exclusive mode;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  unit_id text not null check (btrim(unit_id) <> ''),
  preferred_name text not null check (btrim(preferred_name) <> ''),
  phone_normalized text not null check (phone_normalized ~ '^[0-9]{10,15}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (unit_id, phone_normalized)
);

create table if not exists public.service_sessions (
  id bigint generated by default as identity primary key,
  unit_id text not null check (btrim(unit_id) <> ''),
  customer_id bigint references public.customers(id) on delete restrict,
  status text not null default 'active',
  started_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_sessions_status_check
    check (status in ('active', 'closed', 'cancelled')),
  constraint service_sessions_closed_at_check
    check (
      (status = 'active' and closed_at is null)
      or (status in ('closed', 'cancelled') and closed_at is not null)
    )
);

alter table public.table_sessions
  add column if not exists service_session_id bigint
    references public.service_sessions(id) on delete restrict;

alter table public.customer_sessions
  add column if not exists customer_id bigint
    references public.customers(id) on delete restrict,
  add column if not exists service_session_id bigint
    references public.service_sessions(id) on delete restrict;

alter table public.customer_sessions
  alter column table_session_id drop not null;

alter table public.orders
  add column if not exists service_session_id bigint
    references public.service_sessions(id) on delete restrict;

create unique index if not exists table_sessions_service_session_unique
  on public.table_sessions(service_session_id)
  where service_session_id is not null;

create index if not exists customers_unit_phone_idx
  on public.customers(unit_id, phone_normalized);

create index if not exists service_sessions_unit_status_idx
  on public.service_sessions(unit_id, status, started_at);

create index if not exists customer_sessions_service_customer_idx
  on public.customer_sessions(service_session_id, customer_id);

create index if not exists orders_service_session_idx
  on public.orders(service_session_id, created_at);

alter table public.customer_sessions
  drop constraint if exists customer_sessions_requires_visit_scope;

alter table public.customer_sessions
  add constraint customer_sessions_requires_visit_scope
    check (table_session_id is not null or service_session_id is not null);

alter table public.customer_sessions
  drop constraint if exists customer_sessions_customer_service_fk;

alter table public.customer_sessions
  add constraint customer_sessions_customer_service_fk
    foreign key (customer_id) references public.customers(id)
    on delete restrict;

create or replace function public.modara_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists customers_touch_updated_at on public.customers;
create trigger customers_touch_updated_at
before update on public.customers
for each row execute function public.modara_touch_updated_at();

drop trigger if exists service_sessions_touch_updated_at on public.service_sessions;
create trigger service_sessions_touch_updated_at
before update on public.service_sessions
for each row execute function public.modara_touch_updated_at();

create or replace function public.modara_normalize_customer_phone(input text)
returns text
language sql
immutable
set search_path = public
as $$
  select regexp_replace(coalesce(input, ''), '\D', '', 'g');
$$;

create or replace function public.modara_backfill_table_service_sessions()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  table_session_row record;
  generated_service_session_id bigint;
  service_status text;
  service_closed_at timestamptz;
begin
  for table_session_row in
    select *
    from public.table_sessions
    where service_session_id is null
    order by id
  loop
    service_status :=
      case
        when table_session_row.status in ('closed', 'cancelled')
          then table_session_row.status
        else 'active'
      end;

    service_closed_at :=
      case
        when service_status in ('closed', 'cancelled')
          then coalesce(table_session_row.closed_at, table_session_row.updated_at, table_session_row.created_at, now())
        else null
      end;

    insert into public.service_sessions (
      unit_id,
      status,
      started_at,
      closed_at,
      created_at,
      updated_at
    )
    values (
      table_session_row.unit_id,
      service_status,
      coalesce(table_session_row.created_at, now()),
      service_closed_at,
      coalesce(table_session_row.created_at, now()),
      coalesce(table_session_row.updated_at, table_session_row.created_at, now())
    )
    returning id into generated_service_session_id;

    update public.table_sessions
    set service_session_id = generated_service_session_id
    where id = table_session_row.id;
  end loop;

  update public.customer_sessions customer_session
  set service_session_id = table_session_record.service_session_id
  from public.table_sessions table_session_record
  where customer_session.table_session_id = table_session_record.id
    and customer_session.service_session_id is null
    and table_session_record.service_session_id is not null;

  update public.orders order_record
  set service_session_id = table_session_record.service_session_id
  from public.table_sessions table_session_record
  where order_record.table_session_id = table_session_record.id
    and order_record.service_session_id is null
    and table_session_record.service_session_id is not null;
end;
$$;

select public.modara_backfill_table_service_sessions();

drop function public.modara_backfill_table_service_sessions();

create or replace function public.modara_guard_customer_session_identity()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  resolved_service_session_id bigint;
  service_customer_id bigint;
begin
  if tg_op = 'UPDATE' then
    if new.id is distinct from old.id
      or new.created_at is distinct from old.created_at then
      raise exception 'customer session structural fields are immutable';
    end if;
  end if;

  if new.table_session_id is not null then
    select service_session_id
    into resolved_service_session_id
    from public.table_sessions
    where id = new.table_session_id;

    if resolved_service_session_id is null then
      raise exception 'table session is missing service session';
    end if;

    if new.service_session_id is null then
      new.service_session_id := resolved_service_session_id;
    elsif new.service_session_id <> resolved_service_session_id then
      raise exception 'customer session service session does not match table session';
    end if;
  end if;

  if new.customer_id is not null and new.service_session_id is not null then
    select customer_id
    into service_customer_id
    from public.service_sessions
    where id = new.service_session_id;

    if service_customer_id is null then
      update public.service_sessions
      set customer_id = new.customer_id
      where id = new.service_session_id
        and customer_id is null;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists customer_sessions_identity_guard
  on public.customer_sessions;
create trigger customer_sessions_identity_guard
before insert or update on public.customer_sessions
for each row execute function public.modara_guard_customer_session_identity();

create or replace function public.modara_guard_order_service_session()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  table_service_session_id bigint;
  customer_service_session_id bigint;
  participant_status text;
begin
  if new.table_session_id is not null then
    select service_session_id
    into table_service_session_id
    from public.table_sessions
    where id = new.table_session_id;

    if table_service_session_id is null then
      raise exception 'table session is missing service session';
    end if;

    if new.service_session_id is null then
      new.service_session_id := table_service_session_id;
    elsif new.service_session_id <> table_service_session_id then
      raise exception 'order service session does not match table session';
    end if;
  end if;

  if new.customer_session_id is not null then
    select service_session_id, account_status
    into customer_service_session_id, participant_status
    from public.customer_sessions
    where id = new.customer_session_id;

    if customer_service_session_id is null then
      raise exception 'customer session is missing service session';
    end if;

    if new.service_session_id is null then
      new.service_session_id := customer_service_session_id;
    elsif new.service_session_id <> customer_service_session_id then
      raise exception 'order service session does not match customer session';
    end if;

    if participant_status in ('closed', 'legacy') then
      raise exception 'closed participant cannot create new consumption';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists orders_service_session_guard on public.orders;
create trigger orders_service_session_guard
before insert or update of table_session_id, customer_session_id, service_session_id
on public.orders
for each row execute function public.modara_guard_order_service_session();

create or replace function public.modara_start_service_session(
  target_unit_id text,
  target_preferred_name text,
  target_phone text,
  target_table_session_id bigint default null,
  target_existing_customer_id bigint default null
)
returns table (
  customer_id bigint,
  service_session_id bigint,
  customer_session_id bigint,
  preferred_name text,
  phone_normalized text,
  returning_customer boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_phone text;
  normalized_name text;
  customer_record public.customers%rowtype;
  table_session_record public.table_sessions%rowtype;
  generated_service_session_id bigint;
begin
  normalized_name := btrim(coalesce(target_preferred_name, ''));
  normalized_phone := public.modara_normalize_customer_phone(target_phone);

  if btrim(coalesce(target_unit_id, '')) = '' then
    raise exception 'unit id is required';
  end if;

  if normalized_name = '' then
    raise exception 'preferred name is required';
  end if;

  if normalized_phone !~ '^[0-9]{10,15}$' then
    raise exception 'valid phone is required';
  end if;

  if target_existing_customer_id is not null then
    select *
    into customer_record
    from public.customers
    where public.customers.id = target_existing_customer_id
      and public.customers.unit_id = target_unit_id
      and public.customers.phone_normalized = normalized_phone;

    if not found then
      raise exception 'customer not found for unit and phone';
    end if;

    returning_customer := true;
  else
    returning_customer := exists (
      select 1
      from public.customers
      where public.customers.unit_id = target_unit_id
        and public.customers.phone_normalized = normalized_phone
    );

    insert into public.customers (
      unit_id,
      preferred_name,
      phone_normalized
    )
    values (
      target_unit_id,
      normalized_name,
      normalized_phone
    )
    on conflict on constraint customers_unit_id_phone_normalized_key
    do update set preferred_name = excluded.preferred_name
    returning * into customer_record;
  end if;

  if target_table_session_id is not null then
    select *
    into table_session_record
    from public.table_sessions
    where id = target_table_session_id
      and unit_id = target_unit_id
      and status = 'active'
    for update;

    if not found then
      raise exception 'active table session not found';
    end if;

    if table_session_record.service_session_id is null then
      insert into public.service_sessions (
        unit_id,
        customer_id,
        status
      )
      values (
        target_unit_id,
        customer_record.id,
        'active'
      )
      returning id into generated_service_session_id;

      update public.table_sessions
      set service_session_id = generated_service_session_id
      where id = table_session_record.id;
    else
      generated_service_session_id := table_session_record.service_session_id;
    end if;
  else
    insert into public.service_sessions (
      unit_id,
      customer_id,
      status
    )
    values (
      target_unit_id,
      customer_record.id,
      'active'
    )
    returning id into generated_service_session_id;
  end if;

  insert into public.customer_sessions (
    table_session_id,
    customer_id,
    service_session_id,
    name,
    display_name,
    phone
  )
  values (
    target_table_session_id,
    customer_record.id,
    generated_service_session_id,
    normalized_name,
    normalized_name,
    normalized_phone
  )
  returning id into customer_session_id;

  customer_id := customer_record.id;
  service_session_id := generated_service_session_id;
  preferred_name := customer_record.preferred_name;
  phone_normalized := customer_record.phone_normalized;

  return next;
end;
$$;

create or replace function public.modara_close_service_session_without_consumption(
  target_service_session_id bigint
)
returns public.service_sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  session_record public.service_sessions%rowtype;
begin
  select *
  into session_record
  from public.service_sessions
  where id = target_service_session_id
  for update;

  if not found then
    raise exception 'service session not found';
  end if;

  if session_record.status = 'cancelled' then
    raise exception 'cancelled service session cannot be closed';
  end if;

  if session_record.status = 'closed' then
    return session_record;
  end if;

  if exists (
    select 1
    from public.orders
    where service_session_id = target_service_session_id
      and status <> 'cancelled'
  ) then
    raise exception 'service session has consumption';
  end if;

  update public.service_sessions
  set status = 'closed',
      closed_at = now()
  where id = target_service_session_id
  returning * into session_record;

  return session_record;
end;
$$;

alter table public.customers enable row level security;
alter table public.service_sessions enable row level security;

revoke all on public.customers from anon, authenticated;
revoke all on public.service_sessions from anon, authenticated;

grant execute on function public.modara_start_service_session(
  text, text, text, bigint, bigint
) to anon, authenticated;

grant execute on function public.modara_close_service_session_without_consumption(
  bigint
) to anon, authenticated;

alter table public.customers replica identity full;
alter table public.service_sessions replica identity full;

do $$
begin
  begin
    alter publication supabase_realtime add table public.service_sessions;
  exception
    when duplicate_object then null;
    when undefined_object then null;
  end;
end $$;

do $$
begin
  if exists (
    select 1
    from public.customer_sessions
    where table_session_id is null
      and service_session_id is null
  ) then
    raise exception 'customer_sessions must keep a table or service session scope';
  end if;

  if exists (
    select 1
    from public.orders order_record
    join public.table_sessions table_session
      on table_session.id = order_record.table_session_id
    where order_record.service_session_id is distinct from table_session.service_session_id
  ) then
    raise exception 'orders service_session_id backfill mismatch';
  end if;
end $$;

commit;
