begin;

do $$
begin
  if to_regclass('public.table_sessions') is null
    or to_regclass('public.customer_sessions') is null
    or to_regclass('public.orders') is null then
    raise exception 'MODARA-002 requires table_sessions, customer_sessions and orders.';
  end if;

  if to_regclass('public.table_account_items') is not null
    or to_regclass('public.table_account_allocations') is not null
    or to_regclass('public.table_account_settlements') is not null then
    raise exception 'MODARA-002 account tables already exist.';
  end if;
end;
$$;

lock table public.table_sessions in share row exclusive mode;
lock table public.customer_sessions in share row exclusive mode;
lock table public.orders in share row exclusive mode;

alter table public.customer_sessions
  add column account_status text not null default 'active',
  add column account_closed_at timestamptz;

alter table public.customer_sessions
  add constraint customer_sessions_account_status_check
    check (account_status in ('active', 'closed', 'legacy')),
  add constraint customer_sessions_account_closed_at_check
    check (
      (account_status = 'active' and account_closed_at is null)
      or (account_status in ('closed', 'legacy') and account_closed_at is not null)
    ),
  add constraint customer_sessions_id_table_session_unique
    unique (id, table_session_id);

update public.customer_sessions customer
set account_status = 'legacy',
    account_closed_at = coalesce(customer.updated_at, customer.created_at, now())
from public.table_sessions table_session
where table_session.id = customer.table_session_id
  and table_session.status = 'closed';

create table public.table_account_items (
  id bigint generated by default as identity primary key,
  table_session_id bigint not null references public.table_sessions(id) on delete restrict,
  order_id bigint not null references public.orders(id) on delete restrict,
  order_item_index integer not null check (order_item_index >= 0),
  product_id bigint,
  item_name text not null check (btrim(item_name) <> ''),
  unit_price_cents bigint not null check (unit_price_cents >= 0),
  quantity integer not null check (quantity > 0),
  total_cents bigint not null check (
    total_cents >= 0 and total_cents = unit_price_cents * quantity
  ),
  source_customer_session_id bigint,
  allocation_version integer not null default 0 check (allocation_version >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, order_item_index),
  foreign key (source_customer_session_id, table_session_id)
    references public.customer_sessions(id, table_session_id) on delete restrict
);

create table public.table_account_allocations (
  id bigint generated by default as identity primary key,
  account_item_id bigint not null references public.table_account_items(id) on delete cascade,
  table_session_id bigint not null references public.table_sessions(id) on delete restrict,
  customer_session_id bigint,
  responsibility_scope text not null check (responsibility_scope in ('participant', 'shared')),
  amount_cents bigint not null check (amount_cents > 0),
  quantity integer check (quantity is null or quantity > 0),
  fraction_numerator integer check (fraction_numerator is null or fraction_numerator > 0),
  fraction_denominator integer check (fraction_denominator is null or fraction_denominator > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (responsibility_scope = 'participant' and customer_session_id is not null)
    or (responsibility_scope = 'shared' and customer_session_id is null)
  ),
  check (
    (fraction_numerator is null and fraction_denominator is null)
    or (
      fraction_numerator is not null
      and fraction_denominator is not null
      and fraction_numerator <= fraction_denominator
    )
  ),
  foreign key (customer_session_id, table_session_id)
    references public.customer_sessions(id, table_session_id) on delete restrict
);

create table public.table_account_settlements (
  id bigint generated by default as identity primary key,
  table_session_id bigint not null references public.table_sessions(id) on delete restrict,
  customer_session_id bigint,
  responsibility_scope text not null check (responsibility_scope in ('participant', 'shared')),
  amount_cents bigint not null check (amount_cents > 0),
  idempotency_key text not null check (idempotency_key ~ '^[A-Za-z0-9_-]{16,96}$'),
  settled_at timestamptz not null default now(),
  created_by text not null default 'operation' check (btrim(created_by) <> ''),
  unique (table_session_id, idempotency_key),
  check (
    (responsibility_scope = 'participant' and customer_session_id is not null)
    or (responsibility_scope = 'shared' and customer_session_id is null)
  ),
  foreign key (customer_session_id, table_session_id)
    references public.customer_sessions(id, table_session_id) on delete restrict
);

create index table_account_items_table_session_idx
  on public.table_account_items(table_session_id, order_id);
create index table_account_allocations_table_session_idx
  on public.table_account_allocations(table_session_id, customer_session_id);
create index table_account_allocations_item_idx
  on public.table_account_allocations(account_item_id);
create index table_account_settlements_table_session_idx
  on public.table_account_settlements(table_session_id, customer_session_id, settled_at);

create or replace function public.modara_account_rpc_enabled()
returns boolean
language sql
stable
set search_path = public, pg_temp
as $$
  select coalesce(current_setting('modara.account_rpc', true), '') = 'on';
$$;

create or replace function public.guard_customer_session_account_fields()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.id is distinct from old.id
    or new.table_session_id is distinct from old.table_session_id
    or new.created_at is distinct from old.created_at then
    raise exception 'Customer session structural fields are immutable.';
  end if;

  if (new.account_status, new.account_closed_at)
    is distinct from (old.account_status, old.account_closed_at)
    and not public.modara_account_rpc_enabled() then
    raise exception 'Participant account state must be changed through account RPCs.';
  end if;

  if old.account_status in ('closed', 'legacy')
    and new.account_status is distinct from old.account_status then
    raise exception 'Closed participant account state is immutable in V1.';
  end if;

  if old.account_closed_at is not null
    and new.account_closed_at is distinct from old.account_closed_at then
    raise exception 'Participant account closed timestamp is immutable.';
  end if;

  return new;
end;
$$;

create trigger guard_customer_session_account_fields_trigger
before update on public.customer_sessions
for each row execute function public.guard_customer_session_account_fields();

create or replace function public.table_account_open_amount(target_table_session_id bigint)
returns bigint
language sql
stable
set search_path = public, pg_temp
as $$
  with active_allocations as (
    select coalesce(sum(allocation.amount_cents), 0)::bigint as amount_cents
    from public.table_account_allocations allocation
    join public.table_account_items item on item.id = allocation.account_item_id
    join public.orders orders on orders.id = item.order_id
    where allocation.table_session_id = target_table_session_id
      and orders.status <> 'cancelled'
  ),
  settled as (
    select coalesce(sum(amount_cents), 0)::bigint as amount_cents
    from public.table_account_settlements
    where table_session_id = target_table_session_id
  )
  select greatest(active_allocations.amount_cents - settled.amount_cents, 0)
  from active_allocations, settled;
$$;

create or replace function public.guard_table_account_close()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.status = 'closed' and old.status is distinct from 'closed'
    and public.table_account_open_amount(new.id) > 0 then
    raise exception 'Table session cannot close while account responsibility is open.';
  end if;

  return new;
end;
$$;

create trigger guard_table_account_close_trigger
before update of status on public.table_sessions
for each row execute function public.guard_table_account_close();

create or replace function public.materialize_order_account_items()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  item record;
  account_item_id bigint;
  participant_status text;
  unit_cents bigint;
  item_quantity integer;
begin
  if new.table_session_id is null then
    return new;
  end if;

  if new.customer_session_id is not null then
    select account_status into participant_status
    from public.customer_sessions
    where id = new.customer_session_id
      and table_session_id = new.table_session_id
    for update;

    if participant_status is null then
      raise exception 'Customer session does not belong to the order table session.';
    end if;
    if participant_status in ('closed', 'legacy') then
      raise exception 'Closed participant cannot create new consumption.';
    end if;
  end if;

  for item in
    select value, ordinality - 1 as item_index
    from jsonb_array_elements(coalesce(new.items::jsonb, '[]'::jsonb))
      with ordinality
  loop
    if jsonb_typeof(item.value) <> 'object'
      or coalesce(item.value->>'name', '') = ''
      or coalesce(item.value->>'price', '') !~ '^\d+(\.\d+)?$'
      or coalesce(item.value->>'qty', '') !~ '^\d+$' then
      raise exception 'Invalid order item snapshot for account materialization.';
    end if;

    unit_cents := round((item.value->>'price')::numeric * 100)::bigint;
    item_quantity := (item.value->>'qty')::integer;
    if item_quantity <= 0 then
      raise exception 'Order item quantity must be positive.';
    end if;

    insert into public.table_account_items (
      table_session_id,
      order_id,
      order_item_index,
      product_id,
      item_name,
      unit_price_cents,
      quantity,
      total_cents,
      source_customer_session_id
    ) values (
      new.table_session_id,
      new.id,
      item.item_index,
      case
        when coalesce(item.value->>'id', '') ~ '^\d+$'
          then (item.value->>'id')::bigint
        else null
      end,
      item.value->>'name',
      unit_cents,
      item_quantity,
      unit_cents * item_quantity,
      new.customer_session_id
    )
    returning id into account_item_id;

    if new.status <> 'cancelled' and new.customer_session_id is not null then
      insert into public.table_account_allocations (
        account_item_id,
        table_session_id,
        customer_session_id,
        responsibility_scope,
        amount_cents,
        quantity
      ) values (
        account_item_id,
        new.table_session_id,
        new.customer_session_id,
        'participant',
        unit_cents * item_quantity,
        item_quantity
      );
    elsif new.status <> 'cancelled' then
      insert into public.table_account_allocations (
        account_item_id,
        table_session_id,
        customer_session_id,
        responsibility_scope,
        amount_cents,
        quantity
      ) values (
        account_item_id,
        new.table_session_id,
        null,
        'shared',
        unit_cents * item_quantity,
        item_quantity
      );
    end if;
  end loop;

  return new;
end;
$$;

insert into public.table_account_items (
  table_session_id,
  order_id,
  order_item_index,
  product_id,
  item_name,
  unit_price_cents,
  quantity,
  total_cents,
  source_customer_session_id,
  created_at,
  updated_at
)
select
  orders.table_session_id,
  orders.id,
  item.ordinality - 1,
  case when coalesce(item.value->>'id', '') ~ '^\d+$'
    then (item.value->>'id')::bigint else null end,
  item.value->>'name',
  round((item.value->>'price')::numeric * 100)::bigint,
  (item.value->>'qty')::integer,
  round((item.value->>'price')::numeric * 100)::bigint
    * (item.value->>'qty')::integer,
  orders.customer_session_id,
  orders.created_at,
  orders.created_at
from public.orders orders
cross join lateral jsonb_array_elements(coalesce(orders.items::jsonb, '[]'::jsonb))
  with ordinality item(value, ordinality)
where orders.table_session_id is not null
  and jsonb_typeof(item.value) = 'object'
  and coalesce(item.value->>'name', '') <> ''
  and coalesce(item.value->>'price', '') ~ '^\d+(\.\d+)?$'
  and coalesce(item.value->>'qty', '') ~ '^\d+$'
  and (item.value->>'qty')::integer > 0;

insert into public.table_account_allocations (
  account_item_id,
  table_session_id,
  customer_session_id,
  responsibility_scope,
  amount_cents,
  quantity,
  created_at,
  updated_at
)
select
  account_item.id,
  account_item.table_session_id,
  account_item.source_customer_session_id,
  'participant',
  account_item.total_cents,
  account_item.quantity,
  account_item.created_at,
  account_item.updated_at
from public.table_account_items account_item
join public.orders orders on orders.id = account_item.order_id
join public.customer_sessions customer
  on customer.id = account_item.source_customer_session_id
  and customer.table_session_id = account_item.table_session_id
where orders.status <> 'cancelled'
  and customer.account_status = 'active';

insert into public.table_account_allocations (
  account_item_id,
  table_session_id,
  customer_session_id,
  responsibility_scope,
  amount_cents,
  quantity,
  created_at,
  updated_at
)
select
  account_item.id,
  account_item.table_session_id,
  null,
  'shared',
  account_item.total_cents,
  account_item.quantity,
  account_item.created_at,
  account_item.updated_at
from public.table_account_items account_item
join public.orders orders on orders.id = account_item.order_id
join public.table_sessions table_session on table_session.id = account_item.table_session_id
where orders.status <> 'cancelled'
  and orders.customer_session_id is null
  and table_session.status <> 'closed';

create trigger materialize_order_account_items_trigger
after insert on public.orders
for each row execute function public.materialize_order_account_items();

create or replace function public.replace_table_account_item_allocations(
  target_account_item_id bigint,
  expected_allocation_version integer,
  requested_allocations jsonb
)
returns public.table_account_items
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  account_item public.table_account_items%rowtype;
  allocation jsonb;
  allocation_total bigint := 0;
  participant_id bigint;
  scope text;
  amount bigint;
begin
  perform set_config('modara.account_rpc', 'on', true);

  select * into account_item
  from public.table_account_items
  where id = target_account_item_id
  for update;

  if not found then
    raise exception 'Account item not found.';
  end if;

  if account_item.allocation_version <> expected_allocation_version then
    raise exception 'Account allocation changed concurrently.';
  end if;

  if jsonb_typeof(requested_allocations) <> 'array' then
    raise exception 'Allocations must be a JSON array.';
  end if;

  if exists (
    select 1 from public.table_account_settlements settlement
    where settlement.table_session_id = account_item.table_session_id
  ) then
    raise exception 'Settled account responsibilities cannot be redistributed in V1.';
  end if;

  if exists (
    select 1 from public.orders
    where id = account_item.order_id and status = 'cancelled'
  ) then
    raise exception 'Cancelled order items cannot be allocated.';
  end if;

  for allocation in select value from jsonb_array_elements(requested_allocations)
  loop
    scope := allocation->>'responsibilityScope';
    if scope not in ('participant', 'shared') then
      raise exception 'Invalid responsibility scope.';
    end if;

    if coalesce(allocation->>'amountCents', '') !~ '^\d+$' then
      raise exception 'Allocation amount must be an integer in cents.';
    end if;

    amount := (allocation->>'amountCents')::bigint;
    if amount <= 0 then
      raise exception 'Allocation amount must be positive.';
    end if;
    allocation_total := allocation_total + amount;

    if scope = 'participant' then
      if coalesce(allocation->>'customerSessionId', '') !~ '^\d+$' then
        raise exception 'Participant allocation requires a customer session.';
      end if;

      participant_id := (allocation->>'customerSessionId')::bigint;
      if not exists (
        select 1 from public.customer_sessions
        where id = participant_id
          and table_session_id = account_item.table_session_id
          and account_status = 'active'
      ) then
        raise exception 'Participant is not active in this table session.';
      end if;
    end if;
  end loop;

  if allocation_total <> account_item.total_cents then
    raise exception 'Allocations must match the immutable item total.';
  end if;

  delete from public.table_account_allocations
  where account_item_id = account_item.id;

  insert into public.table_account_allocations (
    account_item_id,
    table_session_id,
    customer_session_id,
    responsibility_scope,
    amount_cents,
    quantity,
    fraction_numerator,
    fraction_denominator
  )
  select
    account_item.id,
    account_item.table_session_id,
    case when value->>'responsibilityScope' = 'participant'
      then (value->>'customerSessionId')::bigint else null end,
    value->>'responsibilityScope',
    (value->>'amountCents')::bigint,
    case when coalesce(value->>'quantity', '') ~ '^\d+$'
      then (value->>'quantity')::integer else null end,
    case when coalesce(value->>'fractionNumerator', '') ~ '^\d+$'
      then (value->>'fractionNumerator')::integer else null end,
    case when coalesce(value->>'fractionDenominator', '') ~ '^\d+$'
      then (value->>'fractionDenominator')::integer else null end
  from jsonb_array_elements(requested_allocations);

  update public.table_account_items
  set allocation_version = allocation_version + 1,
      updated_at = now()
  where id = account_item.id
  returning * into account_item;

  return account_item;
end;
$$;

create or replace function public.settle_table_account_responsibility(
  target_table_session_id bigint,
  target_customer_session_id bigint,
  target_responsibility_scope text,
  settlement_idempotency_key text,
  settlement_created_by text default 'operation'
)
returns public.table_account_settlements
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  allocation_total bigint;
  settled_total bigint;
  open_amount bigint;
  settlement public.table_account_settlements%rowtype;
begin
  perform set_config('modara.account_rpc', 'on', true);

  if target_responsibility_scope not in ('participant', 'shared') then
    raise exception 'Invalid responsibility scope.';
  end if;

  if target_responsibility_scope = 'participant' then
    if target_customer_session_id is null then
      raise exception 'Participant settlement requires a customer session.';
    end if;

    perform 1
    from public.customer_sessions
    where id = target_customer_session_id
      and table_session_id = target_table_session_id
    for update;

    if not found then
      raise exception 'Participant does not belong to the table session.';
    end if;
  else
    target_customer_session_id := null;
  end if;

  select coalesce(sum(allocation.amount_cents), 0) into allocation_total
  from public.table_account_allocations allocation
  join public.table_account_items item on item.id = allocation.account_item_id
  join public.orders orders on orders.id = item.order_id
  where allocation.table_session_id = target_table_session_id
    and allocation.responsibility_scope = target_responsibility_scope
    and allocation.customer_session_id is not distinct from target_customer_session_id
    and orders.status <> 'cancelled';

  select coalesce(sum(amount_cents), 0) into settled_total
  from public.table_account_settlements
  where table_session_id = target_table_session_id
    and responsibility_scope = target_responsibility_scope
    and customer_session_id is not distinct from target_customer_session_id;

  open_amount := allocation_total - settled_total;

  if open_amount <= 0 then
    select * into settlement
    from public.table_account_settlements
    where table_session_id = target_table_session_id
      and idempotency_key = settlement_idempotency_key;

    if found then
      return settlement;
    end if;

    raise exception 'Responsibility has no open balance.';
  end if;

  insert into public.table_account_settlements (
    table_session_id,
    customer_session_id,
    responsibility_scope,
    amount_cents,
    idempotency_key,
    created_by
  ) values (
    target_table_session_id,
    target_customer_session_id,
    target_responsibility_scope,
    open_amount,
    settlement_idempotency_key,
    coalesce(nullif(btrim(settlement_created_by), ''), 'operation')
  )
  on conflict (table_session_id, idempotency_key) do nothing;

  select * into settlement
  from public.table_account_settlements
  where table_session_id = target_table_session_id
    and idempotency_key = settlement_idempotency_key;

  if settlement.amount_cents <> open_amount
    or settlement.responsibility_scope <> target_responsibility_scope
    or settlement.customer_session_id is distinct from target_customer_session_id then
    raise exception 'Idempotency key was reused for a different settlement.';
  end if;

  if target_responsibility_scope = 'participant' then
    update public.customer_sessions
    set account_status = 'closed',
        account_closed_at = coalesce(account_closed_at, now())
    where id = target_customer_session_id
      and table_session_id = target_table_session_id
      and account_status = 'active';
  end if;

  return settlement;
end;
$$;

create or replace function public.close_table_account_session(
  target_table_session_id bigint
)
returns public.table_sessions
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  table_session public.table_sessions%rowtype;
  open_amount bigint;
begin
  perform set_config('modara.account_rpc', 'on', true);

  select * into table_session
  from public.table_sessions
  where id = target_table_session_id
  for update;

  if not found then
    raise exception 'Table session not found.';
  end if;

  if table_session.status = 'cancelled' then
    raise exception 'Cancelled table sessions cannot be closed by account.';
  end if;

  open_amount := public.table_account_open_amount(target_table_session_id);
  if open_amount > 0 then
    raise exception 'Table session cannot close while account responsibility is open.';
  end if;

  if table_session.status = 'closed' then
    return table_session;
  end if;

  update public.table_sessions
  set status = 'closed',
      closed_at = coalesce(closed_at, now()),
      updated_at = now()
  where id = target_table_session_id
  returning * into table_session;

  return table_session;
end;
$$;

create or replace function public.guard_table_account_items_immutable()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if not public.modara_account_rpc_enabled() then
    raise exception 'Account item snapshots are immutable.';
  end if;
  return new;
end;
$$;

create trigger guard_table_account_items_update_trigger
before update on public.table_account_items
for each row execute function public.guard_table_account_items_immutable();

create trigger guard_table_account_items_delete_trigger
before delete on public.table_account_items
for each row execute function public.guard_table_account_items_immutable();

create or replace function public.guard_table_account_settlements_immutable()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'Account settlements are immutable.';
end;
$$;

create trigger guard_table_account_settlements_update_trigger
before update on public.table_account_settlements
for each row execute function public.guard_table_account_settlements_immutable();

create trigger guard_table_account_settlements_delete_trigger
before delete on public.table_account_settlements
for each row execute function public.guard_table_account_settlements_immutable();

alter table public.table_account_items enable row level security;
alter table public.table_account_allocations enable row level security;
alter table public.table_account_settlements enable row level security;

create policy "Public can read table account items"
  on public.table_account_items for select
  to anon, authenticated
  using (true);
create policy "Public can read table account allocations"
  on public.table_account_allocations for select
  to anon, authenticated
  using (true);
create policy "Public can read table account settlements"
  on public.table_account_settlements for select
  to anon, authenticated
  using (true);

grant select on public.table_account_items to anon, authenticated;
grant select on public.table_account_allocations to anon, authenticated;
grant select on public.table_account_settlements to anon, authenticated;
grant execute on function public.replace_table_account_item_allocations(bigint, integer, jsonb)
  to anon, authenticated;
grant execute on function public.settle_table_account_responsibility(bigint, bigint, text, text, text)
  to anon, authenticated;
grant execute on function public.close_table_account_session(bigint)
  to anon, authenticated;

alter table public.table_account_items replica identity full;
alter table public.table_account_allocations replica identity full;
alter table public.table_account_settlements replica identity full;
alter table public.customer_sessions replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.table_account_items;
    alter publication supabase_realtime add table public.table_account_allocations;
    alter publication supabase_realtime add table public.table_account_settlements;
    alter publication supabase_realtime add table public.customer_sessions;
  end if;
exception
  when duplicate_object then null;
end;
$$;

do $$
declare
  invalid_allocation_count integer;
  orphan_allocation_count integer;
  over_allocated_count integer;
  under_or_over_allocated_count integer;
  invalid_cancelled_count integer;
begin
  select count(*) into invalid_allocation_count
  from public.table_account_allocations
  where amount_cents <= 0;

  select count(*) into orphan_allocation_count
  from public.table_account_allocations allocation
  left join public.table_account_items item on item.id = allocation.account_item_id
  where item.id is null;

  select count(*) into over_allocated_count
  from (
    select item.id, item.total_cents, coalesce(sum(allocation.amount_cents), 0) as allocated_cents
    from public.table_account_items item
    left join public.table_account_allocations allocation on allocation.account_item_id = item.id
    group by item.id, item.total_cents
    having coalesce(sum(allocation.amount_cents), 0) > item.total_cents
  ) invalid_items;

  select count(*) into under_or_over_allocated_count
  from (
    select item.id, item.total_cents, coalesce(sum(allocation.amount_cents), 0) as allocated_cents
    from public.table_account_items item
    join public.orders orders on orders.id = item.order_id
    join public.table_sessions table_session on table_session.id = item.table_session_id
    left join public.table_account_allocations allocation on allocation.account_item_id = item.id
    where orders.status <> 'cancelled'
      and table_session.status <> 'closed'
    group by item.id, item.total_cents
    having coalesce(sum(allocation.amount_cents), 0) <> item.total_cents
  ) invalid_items;

  select count(*) into invalid_cancelled_count
  from public.table_account_allocations allocation
  join public.table_account_items item on item.id = allocation.account_item_id
  join public.orders orders on orders.id = item.order_id
  where orders.status = 'cancelled';

  if invalid_allocation_count <> 0
    or orphan_allocation_count <> 0
    or over_allocated_count <> 0
    or under_or_over_allocated_count <> 0
    or invalid_cancelled_count <> 0 then
    raise exception 'MODARA-002 account integrity validation failed.';
  end if;
end;
$$;

commit;
