begin;

create table if not exists public.fast_access_events (
  id bigint generated by default as identity primary key,
  unit_id text not null check (btrim(unit_id) <> ''),
  title text not null check (btrim(title) <> ''),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  uses_default_policy boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.fast_access_rules (
  id bigint generated by default as identity primary key,
  unit_id text not null check (btrim(unit_id) <> ''),
  event_id bigint references public.fast_access_events(id) on delete cascade,
  kind text not null check (kind in ('fallback', 'weekly', 'date', 'event')),
  weekday integer check (weekday between 1 and 7),
  effective_date date,
  starts_at time,
  ends_at time,
  timezone text not null default 'UTC' check (btrim(timezone) <> ''),
  access_status text not null check (
    access_status in ('free', 'pending', 'paid', 'waived')
  ),
  amount_cents bigint not null check (amount_cents >= 0),
  label text not null check (btrim(label) <> ''),
  priority integer not null default 0 check (priority >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (access_status <> 'free' or amount_cents = 0),
  check (
    (kind = 'fallback' and event_id is null and weekday is null and effective_date is null)
    or (kind = 'weekly' and event_id is null and weekday is not null and effective_date is null)
    or (kind = 'date' and event_id is null and weekday is null and effective_date is not null)
    or (kind = 'event' and event_id is not null)
  )
);

create table if not exists public.service_session_access (
  id bigint generated by default as identity primary key,
  service_session_id bigint not null references public.service_sessions(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete restrict,
  unit_id text not null check (btrim(unit_id) <> ''),
  event_id bigint references public.fast_access_events(id) on delete restrict,
  access_rule_id bigint references public.fast_access_rules(id) on delete restrict,
  access_status text not null check (
    access_status in ('free', 'pending', 'paid', 'waived')
  ),
  source text not null check (
    source in ('fallback', 'weekly', 'date-override', 'event', 'manual')
  ),
  original_amount_cents bigint not null check (original_amount_cents >= 0),
  applied_amount_cents bigint not null check (applied_amount_cents >= 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  reason text not null check (btrim(reason) <> ''),
  resolved_at timestamptz not null default now(),
  confirmed_by uuid,
  confirmed_at timestamptz,
  snapshot jsonb not null default '{}'::jsonb,
  unique (service_session_id),
  check (access_status <> 'free' or applied_amount_cents = 0),
  check (
    (access_status in ('paid', 'waived') and confirmed_at is not null)
    or access_status in ('free', 'pending')
  )
);

create table if not exists public.fast_access_audit (
  id bigint generated by default as identity primary key,
  unit_id text not null check (btrim(unit_id) <> ''),
  actor_id uuid,
  action text not null check (btrim(action) <> ''),
  subject_type text not null check (btrim(subject_type) <> ''),
  subject_id bigint,
  previous_value jsonb,
  new_value jsonb,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists fast_access_events_unit_time_idx
  on public.fast_access_events(unit_id, active, starts_at, ends_at);
create index if not exists fast_access_rules_unit_lookup_idx
  on public.fast_access_rules(unit_id, active, kind, priority desc);
create index if not exists fast_access_rules_event_idx
  on public.fast_access_rules(event_id)
  where event_id is not null;
create index if not exists service_session_access_unit_status_idx
  on public.service_session_access(unit_id, access_status, resolved_at);
create index if not exists fast_access_audit_unit_created_idx
  on public.fast_access_audit(unit_id, created_at desc);

create trigger fast_access_events_touch_updated_at
before update on public.fast_access_events
for each row execute function public.modara_touch_updated_at();

create trigger fast_access_rules_touch_updated_at
before update on public.fast_access_rules
for each row execute function public.modara_touch_updated_at();

create or replace function public.modara_access_amount_due(
  access_status text,
  amount_cents bigint
)
returns bigint
language sql
immutable
set search_path = public, pg_temp
as $$
  select case
    when access_status = 'pending' then amount_cents
    else 0
  end
$$;

create or replace function public.modara_require_admin()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.modara_is_catalog_admin() then
    raise exception 'forbidden';
  end if;
end;
$$;

create or replace function public.modara_get_access_events_admin_snapshot(
  target_unit_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.modara_require_admin();

  return jsonb_build_object(
    'infrastructureAvailable', true,
    'unitId', target_unit_id,
    'rules', coalesce((
      select jsonb_agg(to_jsonb(rule) order by rule.kind, rule.priority desc, rule.starts_at)
      from public.fast_access_rules rule
      where rule.unit_id = target_unit_id
    ), '[]'::jsonb),
    'events', coalesce((
      select jsonb_agg(to_jsonb(event) order by event.starts_at desc)
      from public.fast_access_events event
      where event.unit_id = target_unit_id
    ), '[]'::jsonb),
    'issues', '[]'::jsonb
  );
end;
$$;

create or replace function public.modara_save_access_event(
  target_event_id bigint,
  target_unit_id text,
  event_title text,
  event_starts_at timestamptz,
  event_ends_at timestamptz,
  event_uses_default_policy boolean,
  event_active boolean,
  audit_reason text default null
)
returns public.fast_access_events
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  previous_event jsonb;
  saved_event public.fast_access_events%rowtype;
begin
  perform public.modara_require_admin();

  if event_ends_at <= event_starts_at then
    raise exception 'event end must be after start';
  end if;

  if target_event_id is not null then
    select to_jsonb(event)
    into previous_event
    from public.fast_access_events event
    where event.id = target_event_id
      and event.unit_id = target_unit_id
    for update;

    if previous_event is null then
      raise exception 'event not found';
    end if;

    update public.fast_access_events
    set title = btrim(event_title),
        starts_at = event_starts_at,
        ends_at = event_ends_at,
        uses_default_policy = event_uses_default_policy,
        active = event_active
    where id = target_event_id
    returning * into saved_event;
  else
    insert into public.fast_access_events (
      unit_id,
      title,
      starts_at,
      ends_at,
      uses_default_policy,
      active
    )
    values (
      target_unit_id,
      btrim(event_title),
      event_starts_at,
      event_ends_at,
      event_uses_default_policy,
      event_active
    )
    returning * into saved_event;
  end if;

  insert into public.fast_access_audit (
    unit_id,
    actor_id,
    action,
    subject_type,
    subject_id,
    previous_value,
    new_value,
    reason
  )
  values (
    target_unit_id,
    auth.uid(),
    case when target_event_id is null then 'create' else 'update' end,
    'fast_access_event',
    saved_event.id,
    previous_event,
    to_jsonb(saved_event),
    audit_reason
  );

  return saved_event;
end;
$$;

create or replace function public.modara_save_access_rule(
  target_rule_id bigint,
  target_unit_id text,
  target_event_id bigint,
  rule_kind text,
  rule_weekday integer,
  rule_effective_date date,
  rule_starts_at time,
  rule_ends_at time,
  rule_timezone text,
  rule_access_status text,
  rule_amount_cents bigint,
  rule_label text,
  rule_priority integer,
  rule_active boolean,
  audit_reason text default null
)
returns public.fast_access_rules
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  previous_rule jsonb;
  saved_rule public.fast_access_rules%rowtype;
begin
  perform public.modara_require_admin();

  if rule_access_status = 'free' and rule_amount_cents <> 0 then
    raise exception 'free access cannot have pending amount';
  end if;

  if not exists (select 1 from pg_timezone_names where name = rule_timezone) then
    raise exception 'invalid rule timezone';
  end if;

  if target_event_id is not null and not exists (
    select 1 from public.fast_access_events event
    where event.id = target_event_id
      and event.unit_id = target_unit_id
  ) then
    raise exception 'event not found for unit';
  end if;

  if target_rule_id is not null then
    select to_jsonb(rule)
    into previous_rule
    from public.fast_access_rules rule
    where rule.id = target_rule_id
      and rule.unit_id = target_unit_id
    for update;

    if previous_rule is null then
      raise exception 'rule not found';
    end if;

    update public.fast_access_rules
    set event_id = target_event_id,
        kind = rule_kind,
        weekday = rule_weekday,
        effective_date = rule_effective_date,
        starts_at = rule_starts_at,
        ends_at = rule_ends_at,
        timezone = rule_timezone,
        access_status = rule_access_status,
        amount_cents = rule_amount_cents,
        label = btrim(rule_label),
        priority = rule_priority,
        active = rule_active
    where id = target_rule_id
    returning * into saved_rule;
  else
    insert into public.fast_access_rules (
      unit_id,
      event_id,
      kind,
      weekday,
      effective_date,
      starts_at,
      ends_at,
      timezone,
      access_status,
      amount_cents,
      label,
      priority,
      active
    )
    values (
      target_unit_id,
      target_event_id,
      rule_kind,
      rule_weekday,
      rule_effective_date,
      rule_starts_at,
      rule_ends_at,
      rule_timezone,
      rule_access_status,
      rule_amount_cents,
      btrim(rule_label),
      rule_priority,
      rule_active
    )
    returning * into saved_rule;
  end if;

  insert into public.fast_access_audit (
    unit_id,
    actor_id,
    action,
    subject_type,
    subject_id,
    previous_value,
    new_value,
    reason
  )
  values (
    target_unit_id,
    auth.uid(),
    case when target_rule_id is null then 'create' else 'update' end,
    'fast_access_rule',
    saved_rule.id,
    previous_rule,
    to_jsonb(saved_rule),
    audit_reason
  );

  return saved_rule;
end;
$$;

create or replace function public.modara_matching_access_rule(
  target_unit_id text,
  target_event_id bigint,
  use_event_default_policy boolean,
  access_moment timestamptz
)
returns public.fast_access_rules
language plpgsql
stable
set search_path = public, pg_temp
as $$
declare
  matched_rule public.fast_access_rules%rowtype;
begin
  if target_event_id is not null and not use_event_default_policy then
    select *
    into matched_rule
    from public.fast_access_rules rule
    where rule.unit_id = target_unit_id
      and rule.active
      and rule.kind = 'event'
      and rule.event_id = target_event_id
      and (rule.starts_at is null or (access_moment at time zone rule.timezone)::time >= rule.starts_at)
      and (rule.ends_at is null or (access_moment at time zone rule.timezone)::time < rule.ends_at)
    order by rule.priority desc, rule.created_at desc
    limit 1;

    if found then
      return matched_rule;
    end if;
  end if;

  select *
  into matched_rule
  from public.fast_access_rules rule
  where rule.unit_id = target_unit_id
    and rule.active
    and rule.kind = 'date'
    and rule.effective_date = (access_moment at time zone rule.timezone)::date
    and (rule.starts_at is null or (access_moment at time zone rule.timezone)::time >= rule.starts_at)
    and (rule.ends_at is null or (access_moment at time zone rule.timezone)::time < rule.ends_at)
  order by rule.priority desc, rule.created_at desc
  limit 1;

  if found then
    return matched_rule;
  end if;

  select *
  into matched_rule
  from public.fast_access_rules rule
  where rule.unit_id = target_unit_id
    and rule.active
    and rule.kind = 'weekly'
    and rule.weekday = extract(isodow from (access_moment at time zone rule.timezone))::integer
    and (rule.starts_at is null or (access_moment at time zone rule.timezone)::time >= rule.starts_at)
    and (rule.ends_at is null or (access_moment at time zone rule.timezone)::time < rule.ends_at)
  order by rule.priority desc, rule.created_at desc
  limit 1;

  if found then
    return matched_rule;
  end if;

  select *
  into matched_rule
  from public.fast_access_rules rule
  where rule.unit_id = target_unit_id
    and rule.active
    and rule.kind = 'fallback'
  order by rule.priority desc, rule.created_at desc
  limit 1;

  return matched_rule;
end;
$$;

create or replace function public.modara_resolve_service_session_access(
  target_service_session_id bigint,
  access_context jsonb default '{}'::jsonb
)
returns public.service_session_access
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  session_record public.service_sessions%rowtype;
  active_event public.fast_access_events%rowtype;
  matched_rule public.fast_access_rules%rowtype;
  saved_access public.service_session_access%rowtype;
  access_moment timestamptz := coalesce(
    nullif(access_context ->> 'resolvedAt', '')::timestamptz,
    now()
  );
  applied_source text;
  applied_amount bigint;
begin
  select *
  into saved_access
  from public.service_session_access
  where service_session_id = target_service_session_id;

  if found then
    return saved_access;
  end if;

  select *
  into session_record
  from public.service_sessions
  where id = target_service_session_id
    and status = 'active'
  for update;

  if not found then
    raise exception 'active service session not found';
  end if;

  select *
  into active_event
  from public.fast_access_events event
  where event.unit_id = session_record.unit_id
    and event.active
    and access_moment >= event.starts_at
    and access_moment < event.ends_at
  order by event.starts_at desc
  limit 1;

  select *
  into matched_rule
  from public.modara_matching_access_rule(
    session_record.unit_id,
    active_event.id,
    coalesce(active_event.uses_default_policy, true),
    access_moment
  );

  if matched_rule.id is null then
    raise exception 'access policy not configured for unit';
  end if;

  applied_source := case matched_rule.kind
    when 'date' then 'date-override'
    else matched_rule.kind
  end;
  applied_amount := public.modara_access_amount_due(
    matched_rule.access_status,
    matched_rule.amount_cents
  );

  insert into public.service_session_access (
    service_session_id,
    customer_id,
    unit_id,
    event_id,
    access_rule_id,
    access_status,
    source,
    original_amount_cents,
    applied_amount_cents,
    reason,
    resolved_at,
    confirmed_by,
    confirmed_at,
    snapshot
  )
  values (
    session_record.id,
    session_record.customer_id,
    session_record.unit_id,
    active_event.id,
    matched_rule.id,
    matched_rule.access_status,
    applied_source,
    matched_rule.amount_cents,
    applied_amount,
    matched_rule.label,
    access_moment,
    case when matched_rule.access_status in ('paid', 'waived') then auth.uid() else null end,
    case when matched_rule.access_status in ('paid', 'waived') then now() else null end,
    jsonb_build_object(
      'rule', to_jsonb(matched_rule),
      'event', case when active_event.id is null then null else to_jsonb(active_event) end,
      'context', access_context
    )
  )
  returning * into saved_access;

  insert into public.fast_access_audit (
    unit_id,
    actor_id,
    action,
    subject_type,
    subject_id,
    previous_value,
    new_value,
    reason
  )
  values (
    session_record.unit_id,
    auth.uid(),
    'resolve',
    'service_session_access',
    saved_access.id,
    null,
    to_jsonb(saved_access),
    'service-session-entry'
  );

  return saved_access;
end;
$$;

create or replace function public.modara_confirm_service_session_access(
  target_access_id bigint,
  target_status text,
  audit_reason text default null
)
returns public.service_session_access
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  previous_access jsonb;
  saved_access public.service_session_access%rowtype;
begin
  perform public.modara_require_admin();

  if target_status not in ('paid', 'waived') then
    raise exception 'manual access confirmation only supports paid or waived';
  end if;

  select to_jsonb(access)
  into previous_access
  from public.service_session_access access
  where access.id = target_access_id
  for update;

  if previous_access is null then
    raise exception 'service session access not found';
  end if;

  update public.service_session_access
  set access_status = target_status,
      applied_amount_cents = 0,
      source = 'manual',
      confirmed_by = auth.uid(),
      confirmed_at = now()
  where id = target_access_id
  returning * into saved_access;

  insert into public.fast_access_audit (
    unit_id,
    actor_id,
    action,
    subject_type,
    subject_id,
    previous_value,
    new_value,
    reason
  )
  values (
    saved_access.unit_id,
    auth.uid(),
    'confirm',
    'service_session_access',
    saved_access.id,
    previous_access,
    to_jsonb(saved_access),
    audit_reason
  );

  return saved_access;
end;
$$;

alter table public.fast_access_events enable row level security;
alter table public.fast_access_rules enable row level security;
alter table public.service_session_access enable row level security;
alter table public.fast_access_audit enable row level security;

revoke all on public.fast_access_events from public, anon, authenticated;
revoke all on public.fast_access_rules from public, anon, authenticated;
revoke all on public.service_session_access from public, anon, authenticated;
revoke all on public.fast_access_audit from public, anon, authenticated;

grant execute on function public.modara_get_access_events_admin_snapshot(text)
  to authenticated;
grant execute on function public.modara_save_access_event(
  bigint, text, text, timestamptz, timestamptz, boolean, boolean, text
) to authenticated;
grant execute on function public.modara_save_access_rule(
  bigint, text, bigint, text, integer, date, time, time, text, text, bigint, text, integer, boolean, text
) to authenticated;
grant execute on function public.modara_resolve_service_session_access(bigint, jsonb)
  to anon, authenticated;
grant execute on function public.modara_confirm_service_session_access(bigint, text, text)
  to authenticated;

alter table public.fast_access_events replica identity full;
alter table public.fast_access_rules replica identity full;
alter table public.service_session_access replica identity full;
alter table public.fast_access_audit replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.fast_access_events;
    alter publication supabase_realtime add table public.fast_access_rules;
    alter publication supabase_realtime add table public.service_session_access;
  end if;
exception
  when duplicate_object then null;
end $$;

insert into public.fast_access_rules (
  unit_id,
  kind,
  weekday,
  starts_at,
  ends_at,
  timezone,
  access_status,
  amount_cents,
  label,
  priority
)
values
  ('quintal-skatepark', 'fallback', null, null, null, 'America/Sao_Paulo', 'free', 0, 'Entrada livre padrão', 0),
  ('quintal-skatepark', 'weekly', 4, '00:00', '20:00', 'America/Sao_Paulo', 'free', 0, 'Quinta com entrada livre até 20h', 20),
  ('quintal-skatepark', 'weekly', 4, '20:00', null, 'America/Sao_Paulo', 'pending', 2000, 'Entrada de quinta após 20h', 10);

commit;
